accessing
exception: anObject

	<generated>
	exception := anObject