accessing
exception
	"Relation named: #exception type: #FastPythonException opposite: #exceptionAssociation"

	<generated>
	^ exception